Cryptography
algorithm-archivists/algorithm-archive pull request #278
Opened 2018-07-19 08:12 UTC by Liikt

I want to add a chapter on cryptography. 

This is a general overview of what's to come. In the future i want to also write a sub chapter on most of the algorithms and concepts I mentioned here with the occasional code example.

2018-07-19 13:51 UTC, julianschacher commented
I resolved the merge conflict.

2018-07-19 20:54 UTC, leios commented
Thanks for the chapter submission! It looks like there is a good amount of text here to review, so give me some time there. As a quick question: will you be adding an initial algorithm with this too?

Also: the redirect is probably not necessary in this case.

2018-07-20 05:03 UTC, Liikt commented
Yeah I would gladly add an algorithm as well. I wanted to do a sub chapter for every "group" of algorithm. So one for older ones (i.e. caeser or substitution cipher), one for DES/AES one for blowfish (maybe i'll look into twofish as well) and one for RSA

2018-07-20 05:04 UTC, leios commented
Ooh, nice. To be clear: those will be additional PR's on top of this one? I can hopefully get to review this on Sunday my time, but if you want to add to the PR, I'll wait.

2018-07-20 05:07 UTC, Liikt commented
Depends on what you prefer i think :D If it's to much work to review several PRs I can add everything here. If not I think just for organizational purposes I would do a PR for every sub chapter.

2018-07-20 05:08 UTC, leios commented
It's the same amount of work to review one PR or multiple ones. I think you are right that multiple PR's are better for organization

2018-08-02 00:17 UTC, leios requested changes
Sorry for taking so long with this. I was working on this review off and on for the past few weeks.

It's a pretty good start, but kinda clunky at times. I added things that I thought would make it an easier read, but it;s sometimes personal opinion.

I think it is missing a lot of information now (mathematical underpinnings, talk of future directions, etc), but I think that information will come with the algorithms as they come in.

2018-08-02 00:17 UTC, leios commented on contents/cryptography/cryptography.md
> +* ECC or Elliptic-curve cryptography. Here you calulate the private and public key from two points on an elliptic curve. This has the positive side effect that you need smaller numbers than non-ECC a
Both of these should be changed to the other format:

> **RSA:** This algorithm calculates a public and a private key from two very large primes. It is (hopefully) near impossible to factor the product of two such primes in a feasable amount of time.

At the end of this section, we need to mention the same thing as above:

> This section is currently a work-in-progress. These methods will also have corresponding chapters in the near future.

2018-08-02 00:17 UTC, leios commented on contents/cryptography/cryptography.md
> +## General principles of Cryptography
I don't know if I understand this section. It seems to be talking about implementation details for creating your own cryptographic system, but that is beyond the scope of the AAA. We care about the algorithms, but not about protecting someone from an attack.

Maybe we should say something like:

> Cryptographic systems are a cornerstone to modern information technology and lie at the heart of everything from WiFi passwords to bank passwords.
If an attacker manages to crack modern cryptographic algorithms, they could cause serious damage.
For this reason, it is important to keep a few things in mind:

From here, I don't know what to add, though. I kinda feel this section should be removed, as none of the following points seem relevant.

2018-08-02 00:17 UTC, leios commented on contents/cryptography/cryptography.md
> +
Somewhere in this article, we need to mention quantum computing. One of the major reasons it is such a big deal is because it has a heck of a lot of raw power that will completely blow modern cryptographic systems out of the water. This is why quantum cryptography is such a hot topic.

I don't know if it should be added here or with the asymmetric stuff.

2018-08-02 16:45 UTC, Liikt commented on contents/cryptography/cryptography.md
> +
It should probably be with the asymmetric stuff, since quantum computing only really affects that because it's good against the descrete logarithm which asymmetric crypto relies on. Symmetric crypto and hashing stays relatively untouched by it

2018-09-17 23:12 UTC, Liikt commented on contents/cryptography/cryptography.md
> +Symmetric cryptography is called symmetric because the way you encrypt a message is the same as the way to decrypt a message.
Okay after reading through that sentence again I realized that this sentence isn't actually correct. The thing that is the same is the key not the encryption/decryption method.

2019-01-03 01:54 UTC, nic-hartley requested changes

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +
@leios There are also several basic assumptions that modern cryptography relies on (if you multiply two large primes, it's hard to get the original primes back out) which other quantum computing techniques (carefully sculpted waveforms + observation) could invalidate, but it's unknown if they will yet. That's... probably too much detail for an introductory thing on crypto in general, though; maybe a linked chapter on quantum-resistant crypto?

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +For some reason beyond my own comprehension, these three people are almost always given the names Alice (sender), Bob (receiver), and Charlie (attacker or eavesdropper).
"Eve" is the most common name for the eavesdropper that I've seen. Charlie is normally a third party in the communication.

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +Cryptographic systems are a cornerstone to modern information technology and lie at the heart of everything from WiFi passwords to bank passwords.
This phrasing is... odd. They're not at the heart of passwords. Maybe more like:

> Encryption algorithms are a cornerstone to modern information technology and keep everything from cat pictures to bank information safe.

Though the "information technology" bit is still awkward.

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +Meaning whenever possible use a widely accepted cryptography library instead of writing your own cypher.
Indent by four spaces to continue the previous bullet point instead of dropping a random paragraph between points.

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +* Because crypto has become such an advanced field cryptosystems should be analyzed by trained professionals.
Maybe make clear that both algorithms and implementations need to be vetted?

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +* With the advances in technology cryptography often hits it's limits.
*its

Also, not all that often -- modern crypto typically stays well ahead of the technological curve, and modern crypto is designed with configurable strength. See, for example, bcrypt, which has a configurable number of rounds, to scale the work done without changing the algorithm. That'll probably stay relevant for decades, unless someone finds a fundamental flaw in the algorithm.

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +To decrypt, simply XOR again with the same second message.
"second message" should probably be "key", for consistency.

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +* **Permutation Cipher**: Here you choose a permutation $$\pi$$ (i.e. $$\pi=(3,1,2,4)$$) and reorder the the letters according to that $$\pi$$ which is the key.
Pi may well be the variable typically used for the permutation, but for clarity's sake, we should probably call it `p` or something less likely to be confused for 3.14159...

2019-01-03 01:54 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +If the message is altered (possibly by Charlie), then the message can no longer be decrypted with Alice's public key.
Also add a sentence about how, without Alice's private key, Eve can't make a message which could be decrypted with Alice's public key.

2019-01-03 10:33 UTC, Liikt commented on contents/cryptography/cryptography.md
> +For some reason beyond my own comprehension, these three people are almost always given the names Alice (sender), Bob (receiver), and Charlie (attacker or eavesdropper).
Eve may be an eavesdropper sure but charlie is a third party in general. And in the case of cryptomethods usually the bad one. I would keep charlie since one desired goal when attacking a crypto system is to alter a message  hence the `(attacker or eavesdropper)`

2019-01-03 10:34 UTC, Liikt commented on contents/cryptography/cryptography.md
> +Cryptographic systems are a cornerstone to modern information technology and lie at the heart of everything from WiFi passwords to bank passwords.
well i guess you are right. I'll be taking out the `password`

2019-01-03 10:37 UTC, Liikt commented on contents/cryptography/cryptography.md
> +* With the advances in technology cryptography often hits it's limits.
I meant here that we always had to scale the algorithms and are looking for better and better algorithms (i.e. ec instead of rsa, md5 being utter garbo for crypto,...)

2019-01-03 10:37 UTC, Liikt commented on contents/cryptography/cryptography.md
> +To decrypt, simply XOR again with the same second message.
Agreed

2019-01-03 10:38 UTC, Liikt commented on contents/cryptography/cryptography.md
> +* **Permutation Cipher**: Here you choose a permutation $$\pi$$ (i.e. $$\pi=(3,1,2,4)$$) and reorder the the letters according to that $$\pi$$ which is the key.
i was going with what i learned at uni and since the AAA is a pretty scientific collection in general i'd say pi is fine here

2019-01-03 10:40 UTC, Liikt commented on contents/cryptography/cryptography.md
> +
I would settle for a small `post quantum` crypto chapter in which we explain the problems and how they are delt with. Though I agree that this would exceed the "Intro to crypto" part of the chapter

2019-01-03 10:40 UTC, Liikt commented on contents/cryptography/cryptography.md
> +Unsurprisingly, one of the first methods of encryption was supposedly developed by Julius Caeser and called the "Caesar Cipher."
Fair point

2019-01-03 22:51 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +For some reason beyond my own comprehension, these three people are almost always given the names Alice (sender), Bob (receiver), and Charlie (attacker or eavesdropper).
@Liikt I see your point, but mine wasn't that it's entirely wrong, just that it should be rephrased to be more correct. Maybe something like:

> ...always given the names Alice (sender), Bob (receiver), and Eve (eavesdropper).

> Additional characters sometimes show up, depending on what's being discussed -- Carol or Charlie could be a generic third participant, and Chuck is a third participant with malicious intent.

That said, given that Alice/Bob/Eve is by far the most common triplet when discussing _cryptography_ specifically -- as in general, your goal is to secure transmissions between Alice and Bob against any Eve out there -- I think they're really all that need to be mentioned. More people will be introduced in descriptions of algorithms or attacks.

2019-01-03 22:53 UTC, nic-hartley commented on contents/cryptography/cryptography.md
> +* With the advances in technology cryptography often hits it's limits.
@Liikt Ahh gotcha. Maybe rephrase it a little, then? Something like:

> Cryptography is always improving as old algorithms get weaker and technology gets more powerful.

Either way works, though, I just misunderstood it the first time.

2021-11-07 17:23 UTC, leios commented
@Liikt similar to #346, I am not making chapters a priority, would you mind either:

1. Helping with this PR
2. Allowing me to work on this PR either by pushing to it or creating a separate PR entirely

If I don't get a response, I will assume 2

2021-11-07 17:29 UTC, Liikt commented
> @Liikt similar to #346, I am not making chapters a priority, would you mind either:
> 
> 1. Helping with this PR
> 2. Allowing me to work on this PR either by pushing to it or creating a separate PR entirely
> 
> If I don't get a response, I will assume 2

I don't mind helping. But you can also feel free to push into PR as you see fit.

2021-11-07 18:13 UTC, leios requested changes
The text here is pretty good. I made a few suggestions (feel free to ignore some of them). Also: it would be nice to have at least one image or something.

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +    Many formerly thought hashing algorithms became obsolete because the computer used to crack them got faster and better.
```suggestion
    Many formerly state-of-the-art hashing algorithms have become obsolete because the computers used to crack them have gotten faster and better.
```

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +    The keys for RSA have to be longer or different and stronger algorithms have to be used.
I almost feel like this sentence could be removed

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +    Another field that cryptography will have to face is Quantum Computing.
```suggestion
    Another field that cryptography will have to face is quantum computing.
```

Probably fine as-is

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +    Quantum Computers will have a big impact on cryptography and especially asymmetric crypto.
```suggestion
    Quantum computers will have a big impact on cryptography and especially asymmetric cryptography.
```

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +    This whole set of problems is summarized in the field of Post-quantum cryptography.
```suggestion
    This whole set of problems is summarized in the field of post-quantum cryptography.
```

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +This section is currently a work-in-progress, and all of these methods will have corresponding chapters in the near future.
Would it be possible to also add some citations here? just add `{{ "thing" | cite}}` and 
```
### Bibliography

{% references %} {% endreferences %}
```
 at the end. Be sure to add the citations to `literature.bib`

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +For example, if Alice wants to send a message to Bob and this message has to kept private Alice will encrypt the message with Bob's private key.
```suggestion
For example, if Alice wants to send a message to Bob and this message has to be kept private, Alice will encrypt the message with Bob's public key.
```

2021-11-07 18:13 UTC, leios commented on contents/cryptography/cryptography.md
> +
Like before, a few references would be nice

2021-12-28 00:35 UTC, Liikt commented on contents/cryptography/cryptography.md
> +For some reason beyond my own comprehension, these three people are almost always given the names Alice (sender), Bob (receiver), and Charlie (attacker or eavesdropper).
Yeah I think I changed my mind on this one now. Eve is better than Charly

2021-12-28 16:41 UTC, leios commented
There are a few small changes here, would you mind if I just committed the changes myself to merge this?

2022-01-31 14:16 UTC, leios commented
This was finalized in #988

2022-01-31 14:16 UTC, closed without merging