IFS Common Lisp implementation
algorithm-archivists/algorithm-archive pull request #722
Opened 2020-07-04 11:49 UTC by Trashtalk217

The outputting to "out.dat" is slightly dirty and can maybe be improved. Otherwise I'm pretty proud of this one.

2020-07-11 17:17 UTC, berquist requested changes

2020-07-11 17:17 UTC, berquist commented on contents/IFS/code/clisp/ifs.lisp
> +    for point = (make-point (random 1.0) (random 1.0)) ; starting point
I think this creates a new `point` on every iteration of the loop, which none of the other implementations do. Can you change it?

2020-07-19 12:41 UTC, Trashtalk217 commented on contents/IFS/code/clisp/ifs.lisp
> +    for point = (make-point (random 1.0) (random 1.0)) ; starting point
Do you mean the `(make-point (random 1.0) (random 1.0))`, because that's only run once. I don't exactly understand what you mean.

2021-08-28 05:04 UTC, ntindle commented
[lang: lisp]

2021-09-06 18:32 UTC, berquist requested changes
Looks good, just a problem with the displayed lines in the text.

2021-09-06 18:32 UTC, berquist commented on contents/IFS/code/clisp/ifs.lisp
> +    for point = (make-point (random 1.0) (random 1.0)) ; starting point
Well, there must be something here that I don't understand, because the code clearly works. I'm fine with it then.

2021-09-06 18:32 UTC, berquist commented on contents/IFS/IFS.md
> +[import:5-13, lang:"lisp"](code/clisp/ifs.lisp)
```suggestion
[import:5-14, lang:"lisp"](code/clisp/ifs.lisp)
```

2021-09-15 16:29 UTC, leios approved these changes
Merged in the suggestion from berquist, so we should be good to merge!

2021-09-15 16:31 UTC, merged