Added flood fill in Coconut
algorithm-archivists/algorithm-archive pull request #743
Opened 2020-08-05 22:39 UTC by Amaras

Here is the new Coconut code for the flood fill chapter.
I don't see how to make the code more functional, sadly, as it's a really iterative method.

There might be a merge conflict with the C code for now, but in the meantime, this PR is waiting for review.

2021-01-01 21:15 UTC, Trashtalk217 requested changes
The .md file still needs some work, but the code compiles runs and succeeds.
It also feels like the Coconut features can be used slightly more.

In conclusion: I've learned a new dialect today and it's pretty neat!

2021-01-01 21:15 UTC, Trashtalk217 commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    # Testing setup
Maybe try to make the tests similair to the Julia tests.

2021-01-01 21:15 UTC, Trashtalk217 commented on contents/flood_fill/code/coconut/flood_fill.coco
> +        print('.', end='')
The `.` is a bit vague, maybe print something slightly more obvious `S` for succes, or maybe just full words: Success and Failure.

2021-01-01 21:15 UTC, Trashtalk217 commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    possible_neighbours = (Point(0, 1), Point(1, 0), Point(0, -1), Point(-1, 0)) |> map$(location.__add__)
PEP8 recommends a maximum line length of 79. And while I think 79 is a very low for line length, this line in particular is a bit long.

2021-01-01 22:27 UTC, Amaras reviewed
So, I know it needs rework, but some points you raised are, I think, not really valid.
I'm glad to see more people work with Coconut, though :D

2021-01-01 22:27 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +def colour(canvas, location is Point, old_value, new_value):
I need to rework the code to remove that function, indeed

2021-01-01 22:27 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +        for neighbour in find_neighbours(canvas, current_location, old_value,
For this one, I think it's a good idea

2021-01-01 22:27 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +        for neighbour in find_neighbours(canvas, current_location, old_value,
I am not sure I see how to do that right away. I probably need to work on it a bit more, but that seems out of my capabilities for now.

2021-01-01 22:27 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    # Testing setup
What do you mean "similar to the Julia tests"?

2021-01-01 22:27 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +        print('.', end='')
I made it to look like how `unittest` runs tests, so that's a revertible design choice

2021-01-02 11:41 UTC, Trashtalk217 commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    for neighbour in find_neighbours(canvas, location, old_value, new_value):
It's definitely a little too long, splitting it up in `neighbours = find_neighbours(...)` and `neighbours |> map$(...)` is probably a good idea.

About the confusion bit. I think that maps are as intuitive as for-loops. It's just that a lot of people only know for-loops, so maps seem weird to them. I may be slightly (very) biased here, as I have some experience with functional programming, so keep that in mind.

2021-01-02 11:47 UTC, Trashtalk217 commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    # Testing setup
Disregard the thing I said. I meant to say that you should probably use the same test as in the Julia implementation, namely:
```
grid = zeros(5,5)
grid[3,:] .= 1
```
But I just realize that you are already doing so. It's just that Julia indexes it's arrays starting at 1. Got confused there.

2021-01-02 11:50 UTC, Trashtalk217 commented
Sometimes I am just wrong, so feel free to call me out. It's only my first time touching the language after all.

2021-08-22 21:46 UTC, Amaras commented
Closing to redo because I did something stupid.

2021-08-22 21:46 UTC, closed without merging