Implement huffman encoding in ocaml
algorithm-archivists/algorithm-archive pull request #750
Opened 2020-09-05 19:10 UTC by shubhamkumar13

References -> https://ocaml.org/learn/tutorials/99problems.html

2020-09-06 22:14 UTC, shubhamkumar13 commented
![huffman code](https://user-images.githubusercontent.com/13629677/92336268-7115e680-f0bc-11ea-822c-6c23efc3044b.png)

This might be the one

2020-09-06 22:24 UTC, leios commented
Just checked, the codebook generated by this tree is also totally valid!

2020-09-10 08:01 UTC, shubhamkumar13 commented
Is there something wrong with the implementation? It was closed if I correctly remember

2020-10-12 23:02 UTC, leios commented
I think this PR is ready for review; however, I don't have ocaml expertise, so if someone else could step in that would be great!

2021-08-28 05:03 UTC, ntindle commented
[lang: ocaml]

2021-08-28 17:36 UTC, Amaras commented
Hum... now that I look at it, you need to insert the code in the chapter (markdown) file before we can merge @shubhamkumar13
I don't really have expertise in OCaml, sadly, so I can't review this PR properly.

2021-09-15 16:40 UTC, leios commented
If the code is alright, we can probably add the line numbers in and merge this soon? I wasn't sure if the comment from @Amaras meant the code looked good or not

2022-01-12 12:35 UTC, ShadowMitia requested changes
Globally it looks good and it works. A few things seem to be a bit more complicated than it should be, I've addressed a couple of them.

I would suggest to also create a separate file for the priority queue (and perhaps for some of the helper functions), since it's not the main point of the chapter, it would make the example more readable. But I don't mind it being all in the same file.

2022-01-12 12:35 UTC, ShadowMitia commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +  (List.fold_left (fun acc x -> x ^ acc) "" new_str, old_str)
You can simplify `char_diff` with (should be a bit more efficient):

```suggestion
let char_diff str ch = 
  let res = String.concat "" (String.split_on_char ch str) in
  (res, str)
```

2022-01-12 12:35 UTC, ShadowMitia commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +
You can simplifyt to:
```suggestion
let str_to_charlist s = List.init (String.length s) (String.get s)

```

2022-01-12 12:35 UTC, ShadowMitia commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +  List.fold_left (fun acc x -> acc ^ x) "" lst
I believe you can replace the function with this
```suggestion
  String.concat "" lst
```

Calling '^' creates a new string at each iteration. `concat` should be more efficient here.

2022-01-12 12:35 UTC, ShadowMitia commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +  List.fold_left (fun acc x -> acc ^ x) ""
You can reuse `list_to_string` here

```suggestion
   list_to_string (List.map (fun x -> encode codebook x) (str_list msg))
```

2022-01-12 12:35 UTC, ShadowMitia commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +                   @ prefixes_of_tree (prefix ^ "1") t1
You can probably simplify this, and avoid the use of `@` here

2022-01-22 06:09 UTC, shubhamkumar13 commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +  List.map char_to_str @@ str_to_charlist msg
The `@@` operator is a function application operator you can alternatively use parens but I usually avoid using parens, it's a habit I picked up using haskell (with `$` operator), if this seems bad I'll remove it

2022-01-22 06:12 UTC, shubhamkumar13 commented
@ShadowMitia thanks for reviewing this I've left a comment related to the `@@` operator, I think I can remove it since it doesn't matter much either way.

I'll try and replace append function usage, I was also curious how you were able to suggest changes in comments I want to try it, it seems a great way to pinpoint changes.

Thanks again!

2022-01-22 07:08 UTC, ShadowMitia commented
@shubhamkumar13 Glad I can help!

For suggestions in github I learned it from [here](https://til.hashrocket.com/posts/szgdi4at59-github-insert-a-suggestion-).

2022-02-15 13:19 UTC, shubhamkumar13 commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +  List.map (fun x -> encode codebook x) @@ str_list msg |>
Yeah I think you are right here, this seems more readable I'll commit this suggestion

2022-02-15 13:22 UTC, shubhamkumar13 commented on contents/huffman_encoding/code/ocaml/huffman.ml
> +                   @ prefixes_of_tree (prefix ^ "1") t1
Maybe using `List.concat` might be more readable. I'll try that

2022-02-15 13:35 UTC, shubhamkumar13 commented
@ShadowMitia I've updated the edits let me know if this looks good, Thanks!

2022-03-01 10:15 UTC, ShadowMitia approved these changes
I think this looks good now. Thanks for the work!

2022-03-01 10:16 UTC, merged