Add Flood Fill in Python
algorithm-archivists/algorithm-archive pull request #753
Opened 2020-09-19 13:39 UTC by lazyprop

2020-10-02 12:39 UTC, Amaras requested changes
Hi, so this PR finally has a review.
There are several little problems that should be addressed, not least of which is the use of a namedtuple for representing your canvas.
Overall, I think it's a good addition to the AAA, though.

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +    return True
This should be a simple return statement like
```python
def inbounds(canvas, p):
    return min(p) >= 0 and p.x < canvas.max_x and p.y < canvas.max_y
```

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +    return neighbors
I would prefer if you would use a generator instead of returning a list, but it works well enough for 4 neighbours

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +    S = list()
The Python style guide recommends that variable names should be in `snake_case`. In particular, they should be in lower case.

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +    S.append(p)
Also, you could just do `s = [p]`, instead of creating an empty list and appending to it.

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +    while len(S) > 0:
Python has the capability of evaluating the "thruthiness" of an object. So the loop condition simplifies to:
```python
while s:
```

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +            S+= find_neighbors(canvas, cur_loc, old_val, new_val)
There should be a space between `s` and `+=`

2020-10-02 12:39 UTC, Amaras commented on contents/flood_fill/code/python/flood_fill.py
> +Canvas = namedtuple("Canvas", "max_x max_y data")
I am not sure this is possible at all. An element of a tuple should probably be immutable itself if you want to avoid errors, while the way you implemented the algorithm is using a list.
Maybe you should consider using a dataclass instead, which doesn't have this restriction.

2020-10-04 10:39 UTC, Amaras approved these changes
This now looks good enough. I have nothing against it now.

2020-10-12 22:38 UTC, leios approved these changes
This PR looks good, a few line numbers need to be fixed!

2020-10-12 22:38 UTC, leios commented on contents/flood_fill/flood_fill.md
> +[import:15-30, lang="python"](code/python/flood_fill.py)
```suggestion
[import:13-28, lang="python"](code/python/flood_fill.py)
```

2020-10-12 22:38 UTC, leios commented on contents/flood_fill/flood_fill.md
> +[import:62-70, lang="python"](code/python/flood_fill.py)
```suggestion
[import:58-66, lang="python"](code/python/flood_fill.py)
```

2020-10-12 22:38 UTC, leios commented on contents/flood_fill/flood_fill.md
> +[import:12-13, lang="python"](code/python/flood_fill.py)
```suggestion
[import:10-11, lang="python"](code/python/flood_fill.py)
```

2020-10-12 22:38 UTC, leios commented on contents/flood_fill/flood_fill.md
> +[import:32-43, lang="python"](code/python/flood_fill.py)
```suggestion
[import:30-39, lang="python"](code/python/flood_fill.py)
```

2020-10-12 22:38 UTC, leios commented on contents/flood_fill/flood_fill.md
> +[import:45-60, lang="python"](code/python/flood_fill.py)
```suggestion
[import:41-56, lang="python"](code/python/flood_fill.py)
```

2020-10-12 22:42 UTC, merged