Rust version of IFS
algorithm-archivists/algorithm-archive pull request #755
Opened 2020-09-30 19:05 UTC by Liikt

I created the IFS in rust. It has to pull in the rand crate though. (Why doesn't rust have a rand lib in the standard lib anyway?)

2020-10-12 23:00 UTC, leios commented
firstly, code looks good and runs fine. I am happy to merge it; however, I still have some lingering questions about running code like this from the AAA (#691). Should we maybe include the Cargo.toml with this? I know it's different than what we did with the other implementations for Rust, but I feel it would help!

2021-08-28 05:01 UTC, ntindle commented
[lang: rust]

2021-12-01 00:59 UTC, stormofice reviewed
Thanks for the PR!

Overall this code looks good to me and seems to be very similar in concept to #896, which makes me want to approve this. 
However I don't feel completely confident in reviewing Rust code, so a second opinion would be good.

I did include a small suggestion to standardize the output file's name, as seen in #961.

2021-12-01 00:59 UTC, stormofice commented on contents/IFS/code/rust/IFS.rs
> +    std::fs::write("./out.dat", out).unwrap();
```suggestion
    std::fs::write("./sierpinski.dat", out).unwrap();
```

2021-12-01 08:16 UTC, ShadowMitia requested changes
Couple of changes are needed to make this compile and remove some tiny warnings.
Otherwise I think it's good!

2021-12-01 08:16 UTC, ShadowMitia commented on contents/IFS/code/rust/IFS.rs
> +        Point{x: 0.5, y: (0.75 as f64).sqrt()},
To avoid clippy warning on this line, I suggest was change to suffix notation.
```suggestion
        Point{x: 0.5, y: 0.75_f64.sqrt()},
```

2021-12-01 08:16 UTC, ShadowMitia commented on contents/IFS/code/rust/IFS.rs
> +use rand::prelude::*;
Depending on the version of `rand` you are using, you can remove the `::prelude`
```suggestion
use rand::*;
```

2021-12-08 18:09 UTC, Amaras commented
Hello @Liikt!
Since this has an external dependency (namely the `rand` crate), we now require a `cargo.toml` file for compilation (for automated compilation).
Could you please add the file in if you have some time?

2021-12-28 00:32 UTC, Liikt commented
I have commited the suggested changes and a cargo toml

2021-12-28 08:41 UTC, ShadowMitia approved these changes
Looks good to me, thanks!

2021-12-28 08:48 UTC, merged