Remove color function from flood fill because it is redundant
algorithm-archivists/algorithm-archive pull request #766
Opened 2020-10-13 22:38 UTC by leios

Direct fix for #765 

Because the color function is essentially a bounds check before coloring and the bounds check is done upon querying neighbors, it's not necessary to check on color as well.

I have removed the function and the text associated with it.

This might also change code in #752 and #743

2020-10-14 06:52 UTC, lazyprop commented
This also adds the unnecessary `a.out` binary.

2020-10-15 01:51 UTC, berquist requested changes
I've confirmed that this works and the book output is correct, but the compiled `a.out` binary needs to be removed.

2020-10-15 01:53 UTC, leios commented
Woops. Removed the binary file. Thanks for the catch!

2020-10-15 01:54 UTC, berquist approved these changes

2020-10-15 01:54 UTC, merged