adding some code for stack and queue in python
algorithm-archivists/algorithm-archive pull request #771
Opened 2020-10-16 11:50 UTC by nandiya

code example for queue and stack implementation in python

[x] following rule
[x] Only implement algorithms that are already in the AAA
[x] only one language and one algorithm
[x] already test my code

2020-10-16 11:54 UTC, nandiya commented
@Amaras please review my code and can it be used?

2020-10-16 13:22 UTC, Amaras requested changes
So, I have only done a code review. I don't even discuss the opportunity of adding code example on this chapter...
Don't worry if I'm too harsh, I am usually on code, be it from myself or others.

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            self.stack_list=  Node(val)
Slight formatting problem.
```suggestion
            self.stack_list = Node(val)
```

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            self.stack_list = temp
The way you push to the stack seems weird... You push to the beginning, which is not usual. Why don't you simply use a `list` object instead of your linked list?

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            print ("Stack is Empty")
Why do you need to `print` things, actually? You can do that outside the class, because now it will pollute `stdout` every time you use it...

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            return None
You should probably just raise a `ValueError` exception instead of returning `None`, as the `Node` value can actually be `None`, and it doesn't help you programmatically differentiate between a `None` value, and an empty `Stack`

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            return pop_val
Okay, so that is consistent with the way you push, I just have problems with the `print` thingy.

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        while(temp.next != None):
There are several weird things in this line: the redundant parentheses in the `while` loop, the `temp.next != None` which should be `temp.next is not None`, or even simply `temp.next `.

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            while(curr.next != None):
Okay, so the need to have a `while` loop means your underlying data structure is not useful for your usage.
A queue should have fast insertion on one end and fast popping on the other. While I see that your dequeueing is correct, having slow insertion defeats the purpose of he queue...

2020-10-16 13:22 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        while(curr.next != None):
`get_front` should probably be a constant time operation, not a linear time one. I'm sorry, but your Queue implementation is not correct... You need to rework it.

2020-10-16 13:29 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        self.next = None
ahh, I thought this folder for basic implementation in python and we can contribute in any language, so that's why i tried to make one.
well in python itself already has list() which we can used simply, so yeah back to my first reason..

2020-10-16 13:30 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        if self.stack_list == None:
hmm.. I'm still quite new with python itself.. is there any different if i use "is" and "==" ?? is there any different in compile or maybe something else?

2020-10-16 13:30 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            self.stack_list=  Node(val)
ah yeah, forgot to use black XD, my mistake, ty

2020-10-16 13:32 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            self.stack_list = temp
ahh this is back to the first reason.. i'm just implementing the basic way with python, and yeah I thought u're one of the reviewer, bcs I saw your name merged it, sorry abt that

2020-10-16 13:41 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            self.stack_list=  Node(val)
done

2020-10-16 13:41 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            print ("Stack is Empty")
done

2020-10-16 13:41 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            return None
done

2020-10-16 13:41 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +            return pop_val
done

2020-10-16 13:43 UTC, nandiya commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        while(temp.next != None):
done

2020-10-16 13:50 UTC, Amaras commented on contents/stacks_and_queues/code/python/stack_queue.py
> +        if self.stack_list == None:
The problem is that the behaviour of `==` depends on how `__eq__` is implemented for the class you consider (you could possibly have all your `Node` addresses be equal to `None`), while `is` directly compare memory addresses of the two objects, making it more efficient, and ultimately more secure to compare identity rather than equality for None

2021-08-28 04:53 UTC, ntindle commented
[lang: python]

2021-09-15 16:50 UTC, leios commented
What is the state of this PR? I think there are a few lingering changes to be made, but after that, we now have code for stacks and queues, so this can probably be merged in

2021-10-22 23:11 UTC, Amaras requested changes
OK, so I still have some problems with your code, but overall it's more an inconsistency.

I'd prefer the code to be more pythonic (mainly that would mean using the `__str__` method instead of the `print` method, and removing the abbreviations) before merging, though, if you're still into that.

2021-10-23 19:41 UTC, henrikac reviewed
It looks like you have switched stack and queue around. Your stack adds and removes items to/from the beginning of the stack, and your queue to the end. This is, to my understanding, usually the other way around and the other language implementations also does it this way.

2023-03-30 13:44 UTC, closed without merging