Added Cooley-Tukey in Common Lisp
algorithm-archivists/algorithm-archive pull request #786
Opened 2020-11-11 21:15 UTC by 0xJonas

Essentially a port of my Scala PR (#746) which appears to be stuck in review.

2020-12-27 19:34 UTC, Trashtalk217 requested changes
An excellent submission, glad that you're interested @0xJonas. I've been the single person implementing the algorithms in Common Lisp up until now and I'm happy to see another Lisper in the archive.

One last thing, It would maybe help to put some extra comments throughout the code. The archive tries to provide good code examples for people learning programming languages and it can be helpful to provide some extra information.

The code is still fine as is, however, and if you correct the small formatting problems, it should be ready for merging.

2020-12-27 19:34 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +  "Performs the DFT using the iterative Cooley-Tukey method."
Are we doing a DFT or an FFT, wording gets somewhat confusing here.

2020-12-27 19:34 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +  "Actual iterative implementation of the Cooley-Tukey method."
I understand what you're trying to say here with 'iterative,' but it's still recursive. Maybe clarify with a comment. Maybe I'm just nitpicking.

2020-12-27 19:34 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +(defun reverse-bits (value num-bits)
A very clever way of reversing bits, good job!

2020-12-27 19:34 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +  (if (<= (length data) 1)
The general formatting in use for 'if'-statements is:
```
(if (foo 42)
    (bar 12)
    (baz 103))
```
So add a couple of extra spaces.

2020-12-27 19:34 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +  (exp (- (/ (* #c( 0 1) 2.0 pi time-index freq-index)
One space too many
```suggestion
  (exp (- (/ (* #c(0 1) 2.0 pi time-index freq-index)
```

2020-12-27 22:59 UTC, 0xJonas commented
- Changed indentation on the if-statements
- Fixed that one whitespace
- Made iterative implementation use a loop. It is actually much simpler now.
- Added comments

2020-12-28 13:31 UTC, Trashtalk217 requested changes
Thank you for the quick response, I assumed that you were going to do points for sentences, so I left some suggestions for the comments.

I've rechecked some of the other common lisp code and how comments and docstrings are handled is all over the place (even when one person made all of them), so don't worry about it. Just make sure it's consistent within the file.

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +        ;; Split input into even and odd indices into two smaller lists.
```suggestion
        ;; Split even and odd indexed elements into two seperate lists.
```

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +      ;; Split bits into two parts
```suggestion
      ;; Split bits into two parts.
```

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
>    "Combines the FFTs of the even and odd indices"
```suggestion
  "Combines the FFTs of the even and odd indices."
```

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +         ;; Multiply values with coefficients
```suggestion
         ;; Multiply values with coefficients.
```

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +    ;; Combine the two FFTs
```suggestion
    ;; Combine the two FFTs.
```

2020-12-28 13:31 UTC, Trashtalk217 commented on contents/cooley_tukey/code/clisp/fft.lisp
> +          ;; combine them into the Fourier Transform for the full input.
```suggestion
          ;; combine them into the Fourier Transform of the full input.
```

2020-12-28 19:55 UTC, 0xJonas commented
Oops, I forgot to update a line number after the previous commit.

2021-01-01 13:02 UTC, Trashtalk217 approved these changes

2021-01-01 13:03 UTC, Trashtalk217 commented
Sorry for the late confirmation, I misunderstood something. But it's good to merge!

2021-01-01 13:17 UTC, merged