Re-added flood fill in Coconut (without the stupid master merge)
algorithm-archivists/algorithm-archive pull request #836
Opened 2021-08-22 21:48 UTC by Amaras

This replaces #743, because I merged the master branch, and thought it could have been a good idea.
Anyway, here's the good one, normally. It should have the code in the same state as the last commit from the previous PR.

I'm probably going to delete the old branch in a few days (if I remember it then)

2021-08-22 21:57 UTC, lazyprop commented
@Amaras The `inbounds` check is already being done once in `find_neighbours` so it doesn't need to be done again in the `color` function. I made an issue (#765) regarding this.  Just a friendly reminder :) 
Also, I have already fixed it in the Python implementation so you might want to take a look at it

2021-09-06 15:43 UTC, berquist requested changes
I'm happy with the implementation and clarity, and confirmed it runs under `--strict`, just some minor cleanup stuff.

2021-09-06 15:43 UTC, berquist commented on contents/flood_fill/code/coconut/flood_fill.coco
> +def find_neighbours(canvas, location is Point, old_value, new_value):
I don't like how this carries over the unused `new_value` from the other implementations, which similarly don't use it.

2021-09-06 15:43 UTC, berquist commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    print(TestResults(pass_count, failure_count))
This is a nice touch, but will probably have to be reworked when output standardization is done.

2021-09-06 15:43 UTC, berquist commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    try:
Most of this can be lifted into a single testing function that takes in the fill function as an argument, the starting grid, and the expected final grid, encapsulating the try/except/else logic.

2021-09-06 17:18 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    print(TestResults(pass_count, failure_count))
Definitely, I think we'll just have to remove the `test` function for standardization.

2021-09-06 17:21 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +def find_neighbours(canvas, location is Point, old_value, new_value):
Both `old_value` and `new_value` are used in all currently merged implementations an in mine.

2021-09-06 17:21 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +    try:
Done

2021-09-06 17:22 UTC, lazyprop commented
Also, the `inbounds` check that is being done in `stack_fill`, `queue_fill` and `recursive_fill` can be removed. This is because it is being done once in `find_neighbors`. It need not be checked again. The Julia and Python implementations have been changed accordingly.

2021-09-06 17:25 UTC, Amaras commented
> Also, the `inbounds` check that is being done in `stack_fill`, `queue_fill` and `recursive_fill` can be removed. This is because it is being done once in `find_neighbors`. It need not be checked again. The Julia and Python implementations have been changed accordingly.

You can't ensure the functions are called with a point that is not already in bounds. The initial point is *never* checked otherwise.
I could agree for the `recursive_fill`, but the initial point is always an edge case

2021-09-06 17:50 UTC, berquist commented on contents/flood_fill/code/coconut/flood_fill.coco
> +def find_neighbours(canvas, location is Point, old_value, new_value):
Not in this function.

2021-09-06 17:53 UTC, Amaras commented on contents/flood_fill/code/coconut/flood_fill.coco
> +def find_neighbours(canvas, location is Point, old_value, new_value):
Fair enough, it's now corrected

2021-09-06 18:38 UTC, berquist approved these changes

2021-09-06 18:38 UTC, merged

2021-09-06 20:28 UTC, lazyprop commented
@Amaras you're right. Should this be changed in the other two implementations also?

2021-09-06 21:08 UTC, Amaras commented
> @Amaras you're right. Should this be changed in the other two implementations also?

I don't know, maybe we should rather open an issue for that, especially if an issue was opened to remove the checks.