Add C# implemenation for 1D Convolutions
algorithm-archivists/algorithm-archive pull request #846
Opened 2021-08-25 15:59 UTC by stormofice

Requires .NET 5.0 [[SDK Install instructions](https://dotnet.microsoft.com/download/dotnet/5.0)]

If you want to test this implementation on your machine, create a file in the `code/csharp` directory called `code.csproj` and paste the following into it:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

</Project>
```
Now you can execute `dotnet run` to run the implementation.

2021-08-28 04:51 UTC, ntindle commented
[lang: c#]

2021-09-01 17:48 UTC, Trashtalk217 commented
I've attempted to check your code, but I haven't been able to run it yet. C# environments are a whole thing.

I've been able to check the website build, and there's still quite a lot to do there:
![image](https://user-images.githubusercontent.com/24552941/131719055-796e95a9-fe90-4983-b1e6-f9d9f4c62157.png)
This is showing up in the Julia implementation and I have no clue why it is there.

If you need help with setting up honkit, please let me know.

2021-09-03 18:02 UTC, Trashtalk217 commented
I'll do a code review later, since I don't have much time:

The line numbers in the .md file are off for the Julia imports, make sure that looks good.
You've got an off by one error in your .dat files:

![image](https://user-images.githubusercontent.com/24552941/132048098-5e728dce-4864-46e9-8d4d-529d8a6adfd6.png)

Here are the files generated by the Julia implementation for reference:
[cyclic.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7107754/cyclic.txt)
[full_linear.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7107755/full_linear.txt)
[simple_linear.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7107756/simple_linear.txt)

Don't forget that Julia starts indexing at 1 for arrays and not 0.

2021-09-03 18:21 UTC, stormofice commented
Thanks for the review, I fixed the errors you described above and it now produces the following [seems to be correct] output:
[cyclic.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7107838/cyclic.txt)

2021-09-05 17:26 UTC, Trashtalk217 commented
The off-by-one error I noted for the cyclic convolution also exists in the other two convolutions.
Also, for the full-linear implementation, Julia generates an output file of 399 lines and you generate 400 lines. I'm guessing that that's a bug in the Julia implementation, however.

2021-09-05 23:53 UTC, stormofice commented
Thanks for the review, I forgot about the linear convolutions.

The errors should be fixed now; the full linear output includes a `0.0` at the end which the julia implementation does not, however if you print out the value at `full_linear_output[output_size]` (so the last value in the array) in the julia implementation, it also shows `0.0` and it just does not get written to file (that's my assumption at least).

The following outputs get produced:
[full_linear.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7112529/full_linear.txt)
[simple_linear.txt](https://github.com/algorithm-archivists/algorithm-archive/files/7112530/simple_linear.txt)

2021-09-06 00:01 UTC, jiegillet commented
The line missing is probably because we did a ninja edit on the Julia code here: #854. Before that, there was a `0.0` at the end.

2021-09-06 00:07 UTC, stormofice commented
Oh it's the same PR that caused the problem with the Julia line numbers, I'll copy those changes then into the C# implementation.

2021-09-12 13:04 UTC, stormofice commented
@Trashtalk217 I think that all the aforementioned problems should be fixed now, if you want to take another look at this.

2021-09-14 22:26 UTC, Trashtalk217 requested changes
Of all things that don't matter, this review matters very little. I checked the build - looks good, and the output - also looks good. There's some minor picking at the comments but it looks great otherwise.

(I also used suggestions so you don't have to go into your editor again, I don't want to waste your time by havng you place periods.)

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +        // Julia like modulus function which handles negative values properly
If you say what the thing is, you don't have to tell me what it's like.
```suggestion
        // Modulus function which handles negative values properly.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +        // Assumes that y >= 0
The [styleguide](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) recommends ending your sentences with a '.' 

```suggestion
        // Assumes that y >= 0.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +        // Creates a sawtooth function with the given length
```suggestion
        // Creates a sawtooth function with the given length.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +        // Normalizes the given array
```suggestion
        // Normalizes the given array.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +        // Calculates the norm of the array
```suggestion
        // Calculates the norm of the array.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Convolutional output
```suggestion
            // Convolutional output.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Convolutional output
```suggestion
            // Convolutional output.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Create sawtooth functions for x and y
```suggestion
            // Create sawtooth functions for x and y.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Normalization is not strictly necessary, but good practice
```suggestion
            // Normalization is not strictly necessary, but good practice.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Full convolution, output will be the size of x + y - 1
```suggestion
            // Full convolution, output will be the size of x + y - 1.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Simple boundaries
```suggestion
            // Simple boundaries.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Cyclic convolution
```suggestion
            // Cyclic convolution.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +            // Output convolutions to different files for plotting
```suggestion
            // Output convolutions to different files for plotting.
```

2021-09-14 22:26 UTC, Trashtalk217 commented on contents/convolutions/code/csharp/1DConvolution.cs
> +}
You don't have a new line here, and I don't know if that's okay, but Github seems it's important enough to mention it.

2021-09-14 22:40 UTC, stormofice commented
Should all be fixed now, thanks for the review.

2021-09-14 22:59 UTC, Trashtalk217 approved these changes

2021-09-14 23:04 UTC, merged