Implement Stacks and Queues in Rust.
algorithm-archivists/algorithm-archive pull request #924
Opened 2021-11-08 00:48 UTC by PeanutbutterWarrior

I've done the same as the Java and Typescript examples code-wise, however I've added minimal code comments. One is Rust specific, pointing out where a reference is returned instead of the value due to the borrow checker. I've also added comments after the print statements in the test to show the output of them.

2021-11-08 12:27 UTC, henrikac reviewed
looks fine to me

2021-11-26 16:26 UTC, ishwar00 commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            None
is it safe return None as front element when Queue is empty?

2021-11-26 16:28 UTC, ShadowMitia commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            None
What do you mean safe?
You're returning an `Option<>` so returning a `None` is one of the expected values.

2021-11-26 17:03 UTC, ishwar00 commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            None
Okay _safe_ may not be correct word here.
I thought like, say i was doing something like `Q.front() * 5`, then returning `None` would not be right thing to do, right? instead executing `panic!("Attempt to access element from a empty Queue")` may be helpful.

2021-11-26 17:18 UTC, ShadowMitia commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            None
You can't do `Q.front() * 5` anyway with an `Option`. `panic!` is not an exception, you are crashing the application to say something bad happened (and implied unrecoverable, which is not the case here).

Plus `panic!` only works at runtime, which is kinda late to warn on possible problems.

When you write a public facing function, you have to define what the function takes and returns. You could only return `T`, and crash/exception/error handle.  
But `Option` says, "ok we can have either a legit value or `None`". 
That `None` can mean many things, but it describes that no valid data can be returned. And you don't want your user to fall into cases where you get weird/undefined behaviours, so being explicit helps a lot. And the programmer than has to deal with the different cases (or can take shortcuts if he knows that special cases can't happen). 

You don't really care what the programmer does, what you do care about is correctly defining and documenting what your function does, deosn't do, and special cases. And there is always several ways to do that, but I think in this case having `Option` does the job well enough.

You can see in the standard library for example [here](https://doc.rust-lang.org/stable/std/collections/struct.VecDeque.html#method.front) that `Optional` is also used in similar cases.

2021-11-26 17:31 UTC, ishwar00 commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            None
Thank you for being so kind. 
You completely make sense.

2021-11-29 11:00 UTC, ShadowMitia requested changes

2021-11-29 11:00 UTC, ShadowMitia commented on contents/stacks_and_queues/code/rust/Stack.rs
> +            Some(&self.list[self.list.len() - 1])
It might best to use the methods in `Vec` for this
```suggestion
            self.list.last()
```

2021-11-29 11:00 UTC, ShadowMitia commented on contents/stacks_and_queues/code/rust/Queue.rs
> +            Some(&self.list[0])
It might best to use the methods in VecDeque for this
```suggestion
            self.list.front()
```

2021-11-29 17:45 UTC, ShadowMitia requested changes
This looks good overall. Could you just add a `Cargo.toml` and I think we should be good.

I think this should be enough, but feel free to edit it.

```
[package]
name = "stack_and_queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
path = "./Queue.rs"
name = "queue"

[[bin]]
path = "./Stack.rs"
name = "stack"
```

2021-11-29 18:33 UTC, PeanutbutterWarrior commented
Like I've said before, if the name of the built binary isn't _main_ then it won't be copied into the build directory by SConscript. Cargo can't build both files because into _main_, so I think that we should leave it to be compiled with rustc.

SCons can't do multiple files from the same chapter yet, which will need fixing for #950 as you pointed out there. I think it might be best to hold off merging this PR (and #950) until we work that out.
We could also add a special case SConscript file here to deal with this, but as it's probably going to crop up again elsewhere we should make it work by default

2021-11-29 18:56 UTC, ShadowMitia commented
Right I forgot about that. #950 is for interpreted languages, it doesn't really make sense to modify Rust stuff there. It's best to find a solution separately (unless it's convenient all at once I guess).
I'll approve this PR then, @Amaras what do you suggest we do regarding the scons stuff?

2021-11-29 18:56 UTC, ShadowMitia approved these changes

2021-11-29 19:33 UTC, Amaras commented
> I'll approve this PR then, @Amaras what do you suggest we do regarding the scons stuff?

Since both files have a main function, the smartest move in my opinion would be to put a SConscript with two distinct rustc targets (say `build/rust/stack` and `build/rust/queue`).

We'll merge once this is done, since there already is an approval.

2021-11-29 21:48 UTC, PeanutbutterWarrior commented
I've had to rebase in order to get the latest SCons updates, as this branch was created before most of it. No conflicts had to be resolved. Git was confused, so I had to force push. I've added the SConscript file and checked that it builds

2021-11-29 22:09 UTC, Amaras approved these changes
Alright, the SCons part looks good to me.

We'll just need to merge the master branch correctly and it'll be good.﻿

2021-12-02 15:51 UTC, leios commented
Is there anything holding this PR back? I think it's mergable, but am not sure why we waited before

2021-12-02 16:18 UTC, merged