New chapter "Metropolis" with Python Implementation
algorithm-archivists/algorithm-archive pull request #929
Opened 2021-11-10 04:53 UTC by shudipto-amin

2021-11-10 19:59 UTC, PeanutbutterWarrior commented
I feel like this would make more sense grouped together with monte carlo under "Monte Carlo Methods", and rename monte carlo to "Approximating areas"

2021-11-10 20:20 UTC, PeanutbutterWarrior commented
I dislike using numpy. It's specialised enough that not everyone will know it, and it has no counterpart in many languages. It could be replaced here with `math.e^(-b1*(x-x1)**2)`, and `random.uniform(-1, 1)`.

2021-11-10 20:24 UTC, shudipto-amin commented
> I feel like this would make more sense grouped together with monte carlo under "Monte Carlo Methods", and rename monte carlo to "Approximating Areas"

I agree - they belong in a similar category.

2021-11-10 20:31 UTC, henrikac commented on contents/metropolis/code/python/metropolis.py
> +import matplotlib.pyplot as pp
I'm not sure why `matplotlib` is imported because I don't see it used anywhere? :)

2021-11-10 20:38 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +import matplotlib.pyplot as pp
My bad! I was plotting with it, but then forgot to remove it. That line can be deleted.

2021-11-10 20:45 UTC, shudipto-amin commented
> I dislike using numpy. It's specialised enough that not everyone will know it, and it has no counterpart in many languages. It could be replaced here with `math.e**(-b1*(x-x1)**2)`, and `random.uniform(-1, 1)`.

I'm not sure I agree, but I see where you're coming from, with `math` and `random` being built in libraries. Also, a bunch of other code on AAA uses numpy quite a bit. But perhaps here we don't need to use it, as it doesn't simplify the code like in the others. I am okay with changing it.

2021-11-10 21:02 UTC, shudipto-amin commented on literature.bib
> +Equation of State Calculations by Fast Computing Machines
Oops, these lines are unnecessary and should be deleted.

2021-11-12 16:36 UTC, leios reviewed
Overall, I think the quality here is good. I a few lingering remarks that I didn't mention yet:

1. I think random walk should not be capitalized in the text body
2. It would be nice to talk briefly about how this is used in practice. I know it's used a lot in various physical applications, so maybe pointing to those with citations would be nice. I like that the code is for a general PDF, but maybe mentioning Mawell--Boltzmann or something would make the physics folk happy

2021-11-12 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +### Any symmetric function can be used to generate the step
I think this entire paragraph is really important and should be moved up before the example code to where you talk about the definition of `g()`

2021-11-12 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +### A runaway walker
I don't know if I fully understand this section. Maybe a visualization would help?

Also: it might be a good idea to move this above the example code?

2021-11-12 16:36 UTC, leios commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
It might be nice to pre-allocate the array for performance (although I don't know python super well)

2021-11-12 16:36 UTC, leios commented on contents/metropolis/code/python/metropolis.py
> +
It would be nice to have some sort of test to show that we are generating the correct function. An example test can be found in the [Approximate Counting Algorithm](https://www.algorithm-archive.org/contents/approximate_counting/approximate_counting.html)

2021-11-12 16:39 UTC, leios commented
For numpy, I think it's fine in this case. As someone coming from an HPC background, I genuinely thought the first thing everyone did when using python was to import numpy. I think we should be cognizant of the fact that this is not true for everyone and maybe remove numpy from less numerical methods.

2021-11-12 17:43 UTC, Amaras requested changes
Alright, I don't have anything to add to the chapter review.
I have a few problems, though:
1. If you don't really use numpy features in your implementation, just don't import numpy. `math` functions are usually just as fast for non-vectorised calls, and I don't know much of the stdlib implementation of `random` to tell if `numpy.random` is faster or not.
2. You are technically not assured that `f` will not be 0, so that might get you into trouble

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +           a3*np.exp( -b3*(x-x3)**2 )
PEP8 concern:
```suggestion
    return (
           a1 * np.exp(-b1 * (x - x1)**2) + 
           a2 * np.exp(-b2 * (x - x2)**2) + 
           a3 * np.exp(-b3 * (x - x3)**2)
        )
```

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +def iterate(x, f=f, g=g):
The naming feels confusing to me. Shouldn't `iterate` do the complete loop?

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
If performance really is an issue, I would recommend pre-allocating indeed.
I don't think this is really the case here, though.

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +        x_new = x
Fair enough, but wouldn't `np.random.choice` be a better function for this?, something like this:
```suggestion
x_new = np.random.choice([x_proposed, x], p=[A, 1-A])

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +    A = min(1, f(x_proposed)/f(x) )
PEP8 recommends snake_case for variables in Python
```suggestion
    a = min(1, f(x_proposed) / f(x))
```

2021-11-12 17:43 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +    N = 50_000   # no. of iterations
Same problem as for `A`

2021-11-12 17:49 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +def iterate(x, f=f, g=g):
Hmm, would  `metropolis_step` or `one_complete_step` be better?

2021-11-12 17:58 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +        x_new = x
Hmm, yeah that probably makes it easier to understand too. The whole `if u <= A` code block is just how the algorithm is written in pseudo code. But it would be far less confusing to say "choose proposed x with probability A", and then use your suggestion. This way we can do away with the variable `u` completely.

2021-11-12 18:25 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +def iterate(x, f=f, g=g):
`metropolis_step` sounds better for me

2021-11-13 04:49 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +def iterate(x, f=f, g=g):
```suggestion
def metropolis_step(x, f=f, g=g):
```

2021-11-13 04:52 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +        x_new = x
```suggestion
    x_new = np.random.choice([x_proposed, x], p=[a, 1-a])
```

2021-11-13 04:58 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    N = 50_000   # no. of iterations
```suggestion
    num_steps = 50_000
```

2021-11-13 04:58 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    for n in range(N):
```suggestion
    for n in range(num_steps):
```

2021-11-13 16:44 UTC, shudipto-amin commented on contents/metropolis/metropolis.md
> +where $$D$$ is the domain of $$P(\mathbf{x})$$, i.e., all possible values of the coordinates $$\mathbf{x}$$ for which $$P(\mathbf{x})$$ is defined.
I think your comments are all good points, and I realize now that my introduction kind of blows. It is rushed, and assumes a lot of background from the reader. I think the way to make the intro better would be:

1. Add a subsection answering the question "What is a probability density function?" which would cover normalization and why normalization is difficult, with an example.
2. An "Applications" subsection which covers certain application areas like creating a Boltzmann distribution (or just distribution) of a system of particles. A good opportunity to cite more papers here too!

2021-11-15 01:44 UTC, shudipto-amin commented on contents/metropolis/metropolis.md
> +This is especially true when the coordinates ($$\mathbf{x}$$) are multidimensional, and $$f(\mathbf{x})$$ is an expensive calculation. One example use case is a multidimensional physical system with
I'm providing a Gaussian example, as well as an entire section for application :)

2021-11-15 03:29 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
I did some research and  tried a few methods of pre-allocating - it turns out python lists aren't that efficient when pre-allocated, and appending turns out to be faster, surprisingly - or at best pre-allocating is about the same. Normally, for large iterations I believe we would just skip arrays altogether and just write directly to file after certain intervals.

2021-11-15 04:52 UTC, shudipto-amin commented
Okay, I added a new section to Metropolis chapter on applications. I also created a new chapter on Probability Distributions which is linked to in the Metropolis chapter. Also added a bunch of citations and hopefully clarified a few points.

2021-11-15 23:14 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
I was thinking in terms of numpy arrays, rather than Python lists.
In the case of lists, the memory structure makes it hard to optimise by pre-allocation

2021-11-16 19:42 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
The main reason I didn't use numpy array in this case was because iterating over and changing a numpy array is actually slower than simply appending to a python list. I tried a few things, like using `np.nditer` and `np.ndenumerate`, but while those are fast at just reading the array, I couldn't make the process of re-assigning elements of an numpy array any faster. 

I think the main problem here is that the `metropolis_step()` function is not vectorizable. Eg. `y = some_function_of(x)`, is indeed vectorizable and much faster with numpy.  But what we have `x[ind] = some_function_of(x[ind -1])`, which is not vectorizable, and we have to explicitly loop through and assign elements of an ndarray - a slow process. What I usually do in this scenario is to use the package `numba`, which makes iterating over a pre-allocated numpy array super fast. But for the sake of this example, do we want to import more packages? Or is there some other trick that I'm unaware of?

2021-11-16 20:23 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
> But for the sake of this example, do we want to import more packages? 

We only assume that the standard library, `numpy` and `matplotlib` are installed for Python, to have a somewhat standard, semi-minimalist, environment. I don't think we want to have `numba` installed as well.

> The main reason I didn't use numpy array in this case was because iterating over and changing a numpy array is actually slower than simply appending to a python list. I tried a few things, like using `np.nditer` and `np.ndenumerate`, but while those are fast at just reading the array, I couldn't make the process of re-assigning elements of an numpy array any faster.

Okay, fair enough. You might not want to not use `numpy.random` functions then, because it's probably not really worth it to import `numpy` in that case.
Maybe using a generator would be better here (rather than a list), but that can be confusing to beginners, so even though I'd recommend it in production code, I don't think it's necessary here.

2021-11-16 22:39 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    x_dat = [x0]  # for storing values
Might need to keep `numpy` after all - I realise now that the 'test' Leios is asking for requires calculating a histogram, which would be harder and slower to do without `numpy`.

2021-11-16 23:24 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +
Done! It doesn't say "pass" or "fail", just tells the % error.

2021-11-17 00:18 UTC, Amaras requested changes
Okay, so there are a few more corrections I'd like to see in the code from the current version. 

Some are not mandatory (transforming `metropolis_iterate` into a generator, using `numpy` arrays in `f`, and returning from `test_metropolis_iterate`), others like using the `%` formatting are definitely better than the current version.

I won't do a review of the probability distributions chapter right now, but I might do later. Leios will be the main chapter reviewer in any case, so...

2021-11-17 05:33 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +        )
I had to modify your code a bit to make it work (because the shape of `x` doesn't match that of `a`,`b`, or `xs` ):
```python
def f(x, normalize=False):
    '''
    Function proportional to target distribution, a sum of Gaussians.
    For testing, set normalize to True, to get target distribution exactly.
    '''
    # Gaussian heights, width parameters, and mean positions respectively:
    a  = np.array([10,   3, 1]).reshape(3, 1)
    b  = np.array([ 4, 0.2, 2]).reshape(3, 1)
    xs = np.array([-4,  -1, 5]).reshape(3, 1)

    if normalize:
        norm = np.sqrt(np.pi) * (a / np.sqrt(b)).sum()
        a /= norm
    return (a * np.exp(-b * (x - xs)**2)).sum(axis=0)
```
I'm okay with this if you are.

2021-11-17 07:59 UTC, Amaras commented on contents/metropolis/code/python/metropolis.py
> +        )
No problem with that, but please don't align numbers or operators (it's not PEP8 compliant)

2021-11-17 23:44 UTC, shudipto-amin commented
> Okay, so there are a few more corrections I'd like to see in the code from the current version.
> 
> Some are not mandatory (transforming `metropolis_iterate` into a generator, using `numpy` arrays in `f`, and returning from `test_metropolis_iterate`), others like using the `%` formatting are definitely better than the current version.
> 
> I won't do a review of the probability distributions chapter right now, but I might do later. Leios will be the main chapter reviewer in any case, so...

I believe the latest push addresses all of the above concerns. Also slighlty modified mardown to add a little discussion about the second video on metropolis walker.

2021-11-22 16:31 UTC, Amaras approved these changes
Okay, the Python part looks good to me :smiley:

2021-11-22 17:19 UTC, leios reviewed
Overall great chapter, I will get back to metropolis tomorrow. Would you be willing to put each sentence on it's own line? This helps with review and also maintainence.

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +So now we the domain of possibilites, i.e., $$n \in [2..12]$$. Next, we take a very common approach - we count up the number of different ways each of the possbile values of $$n$$ can occur. Let's ca
```suggestion
So now we know the domain of possibilities, i.e., $$n \in [2..12]$$. Next, we take a very common approach - we count up the number of different ways each of the possbile values of $$n$$ can occur. Let's call this the frequency, $$f(n)$$ of each possible $$n$$. We already know that $$f(2)=1$$, as there is only one way to get a pair of 1s. For $$n=3$$, we see that there are two possible ways: a $$1$$ and $$2$$, or a $$2$$ and $$1$$, so $$f(3)=2$$. If you continue doing this for all $$n$$, you may see a pattern (homework for the reader!). Once you have all the $$f(n)$$, we can visualize it in a plot,
```

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +The $$f(n)$$ plotted above is technically NOT the probability $$P(n)$$ - because we know that the sum of all probabilities should be 1, which clearly isn't the case for $$f(n)$$. But we can just get
```suggestion
The $$f(n)$$ plotted above is technically NOT the probability $$P(n)$$ - because we know that the sum of all probabilities should be 1, which clearly isn't the case for $$f(n)$$. But we can get the probability by dividing $$f(n)$$ by the _total_ number of possibilities, $$N$$. For two die, that is $$N = 6 \times 6 = 36$$, but we could also express it as the _sum of all frequencies_,
```

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +The $$f(n)$$ plotted above is technically NOT the probability $$P(n)$$ - because we know that the sum of all probabilities should be 1, which clearly isn't the case for $$f(n)$$. But we can just get
I don't know if it's just me, but I have never called these frequencies and find that notation a bit confusing. I usually instead microstate / macrostate notation.

I think there at least needs to be an explicit mention that "frequency here means the number of occurrences of $$n$$ for each number." or something more elegant than that.

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +Note that $$f(n)$$ does not necessarily have to be the frequency of $$n$$ - it could really be any function which is _proportional_ to $$P(n)$$, and the above definition of $$P(n)$$ would still hold.
```suggestion
Note that $$f(n)$$ does not necessarily have to be the frequency of $$n$$ - it could be any function which is _proportional_ to $$P(n)$$, and the above definition of $$P(n)$$ would still hold. And it's easy to check that the sum is now equal to 1, since
```

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +Once we have the probability function $$P(n)$$, we can calculate all sorts of probabilites. For example, let's say we want to find the probability that $$n$$ will be between two integers $$a$$ and $$
```suggestion
Once we have the probability function $$P(n)$$, we can calculate all sorts of probabilites. For example, let's say we want to find the probability that $$n$$ will be between two integers $$a$$ and $$b$$, inclusively (also including $$a$$ and $$b$$). For brevity, we will use the notation $$\mathbb{P}(a \leq n \leq b)$$ to denote this probability. And to calculate it, we simply have to sum up all the probabilities for each value of $$n$$ in that range, i.e.,
```

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +What if instead of a discrete variable $$n$$, we had a continuous variable $$x$$, like temperature or weight? In that case, it doesn't make sense to ask what the probability is of $$x$$ being _exactl
```suggestion
What if instead of a discrete variable $$n$$, we had a continuous variable $$x$$, like temperature or weight? In that case, it doesn't make sense to ask what the probability is of $$x$$ being _exactly_ a particular number - there are infinite possible real numbers, after all, so the probability of $$x$$ being exactly any one of them is essentially zero! But it _does_ make sense to ask what the probability is that $$x$$ will be _between_ a certain range of values. For example, one might say that there is 50% chance that the temperature tomorrow at noon will be between 5 and 15, or 5% chance that it will be between 16 and 16.5. But how do we put all that information, for every possible range, in a single function? The answer is to use a __probability density function__. 
```

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +But what about large ranges of $$x$$, which are not infinitesimally thin? We do exactly what we did for the discrete case - sum up the probabilities of each and every distinct range of values, each w
I feel this last line is out of place a bit. The discussion on discrete PDFs was almost at an undergrad level, while this feels more like high school? I don't know if we need to recap calculus or not?

2021-11-22 17:19 UTC, leios commented on contents/probability/distributions/distributions.md
> +f(x) = e^{-x^2}
You are right that this is the heart of a Gaussian, but I don't know if it's right to call this the normal distribution function without the standard deviation (for example). Maybe say that we "consider the normal distribution function, which boils down to..."

2021-11-23 01:54 UTC, shudipto-amin commented
> Overall great chapter, I will get back to metropolis tomorrow. Would you be willing to put each sentence on it's own line? This helps with review and also maintainence.

I just saw how inconvenient this was for the review on your last stream - so sorry about this! I have modified both files (metropolis and probability chapters) to fix this.

2021-11-23 02:54 UTC, shudipto-amin commented
Just pushed the latest version of this PR, which addresses the recent comments and suggestions by @leios . In particular, this
1. Fixes the line separation issue for each sentence (both metropolis and PDF chapters).
2. Adds lines for implementing MathJax in PDF chapter, as indicated.
3. Adds intro to PDF. 
4. Removes intro to calculus in PDF chapter.
5. Makes discrete probability section more understandable (hopefully).
6. Makes other minor edits.

2021-11-23 13:58 UTC, leios reviewed
On the one hand, the metropolis chapter is looking way better, but on the other hand, I am not sure I fully understand the arguments in the example application

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +# Metropolis Algorithm
```suggestion
# The Metropolis Algorithm
```

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +
```suggestion
The Metropolis algorithm {{ "metropolis1953equation" | cite }} is a slightly more advanced Monte Carlo method which uses random numbers to approximate a [probability distribution](../probability/distributions/distributions.md):

```

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +and $$f(\mathbf{x})$$ is some a function that is proportional to $$P(x)$$, such as a frequency distribution of $$\mathbf{x}$$.
Again, not super clear on what a "frequency distribution" is. Maybe saying "such as the likelihood of particular outcomes in a game of chance."

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +and $$f(\mathbf{x})$$ is some a function that is proportional to $$P(x)$$, such as a frequency distribution of $$\mathbf{x}$$.
It might be nice to explicitly mention that the denominator is normalizing the function?

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> + One example of a complicated probability function arises when considering a physical system of $$N$$ number of particles.
```suggestion
One example of a complicated probability function arises when considering a physical system of $$N$$ particles. 
```

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> + With that speed, it would require $$10^{41}$$ seconds on a single processor to calculate $$Q$$ - which means that _even_ with all the processors in the world running in parallel (there could be bill
I don't know if I buy this. We are giving each of the 10 points in space 50 possible positions to exist in. That might be 10^50 permutations, but it's not clear to me why you need to use every permutation for calculating Q. To me, it seems like you have 10 separate 1D coordinates, not a 10D space, unless there are some weird interaction terms with the particles?

This might make sense, but would be way clearer with a direct expression for Q.

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +What this means for the Botlzmann distribution is that you only need to know the term,
```suggestion
What this means for the Boltzmann distribution is that you only need to know the term,
```

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +And the Metropolis algorithm can bypass calculation of $$Q$$ altogether and use $$f(x)$$ to generate a distribution of $$x$$ which follows the probability density $$P(x)$$.
This is possible because $$Q$$ is essentially just a normalization factor, so finding some other way to evaluate f and doing the normalization after-the-fact can eliminate the Q calculation entirely.

I think it's important to explicitly mention this

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +In other words, it can sample values of $$x$$ in such away that the probability of sampling $$x$$ will follow the actual distribution $$P(x)$$ - the more likely a value of $$x$$ is according to $$P(x
```suggestion
In other words, it can sample values of $$x$$ in such away that the probability of sampling $$x$$ will follow the actual distribution $$P(x)$$. 
```

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +Because the Metropolis algorithm tends toward high probability regions, it's good at sampling those regions and providing us with a realistic collection of systems.
I almost feel like we could completely remove this paragraph without any loss to the chapter. Maybe the main point was a bit too confusing?

2021-11-23 13:58 UTC, leios commented on contents/metropolis/metropolis.md
> +Other algorithms that implement the algorithm are Metropolis-adjusted Langevin algorithm {{ "mala_wiki" | cite }}, and Hamiltonian Monte Carlo {{ "hmc_wiki" | cite }}, to name a few.
```suggestion
Some other algorithms that use this method are Metropolis-adjusted Langevin algorithm {{ "mala_wiki" | cite }}, and Hamiltonian Monte Carlo {{ "hmc_wiki" | cite }}, to name a few. 
```

2021-11-23 17:16 UTC, shudipto-amin commented
> On the one hand, the metropolis chapter is looking way better, but on the other hand, I am not sure I fully understand the arguments in the example application

Addressed your comments regarding this. Particularly, I think the difficulty of calculating $$Q$$ in the example is a bit clearer now.

2021-11-25 13:47 UTC, leios reviewed
I am happy with the probability density section and think it's pretty much ready to go. Now to take a closer look at metropilis.

Thanks again!

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +Similarly, the probability of getting tails (T) is $$P(T) = \frac{1}{2}$$.
```suggestion
Similarly, the probability of getting tails $$(T)$$ is $$P(T) = \frac{1}{2}$$. 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +From the above equation, we can also assume that any other outcome for $$n$$ (such as landing on an edge) is incredibly unlikely, impossible, or simply "not allowed" (eg. just toss again if it _does_
Maybe "for example" instead of eg. Also, shouldn't it be e. g.?

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +If we use a different system, the outcome $$n$$ could mean other things - it could also be a number.
```suggestion
If we use a different system, the outcome $$n$$ could mean other things.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +For example, the outcome of a __die roll__ has the probability distribution,
```suggestion
For example, it could be a number like the outcome of a __die roll__ which has the probability distribution,
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +		\end{matrix}
```suggestion
		\end{matrix}.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +which is saying that the probability of $$n$$ being a whole number between 1 and 6 is $$1/6$$, and we assume that the probability of getting any other $$n$$ is 0.
```suggestion
This is saying that the probability of $$n$$ being a whole number between 1 and 6 is $$1/6$$, and we assume that the probability of getting any other $$n$$ is 0. 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +The rolling two dice is a great case study for how we can construct a probability distribution, since the probability varies and it is not immediately obvious how it varies.
```suggestion
The example of rolling two dice is a great case study for how we can construct a probability distribution, since the probability varies and it is not immediately obvious how it varies. 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +We know that the lowest sum of two dice is 2 (a 1 on both dice), so $$n \geq 2$$ for sure. Similarly, the maximum is sum of two sixes, or 12, so $$n \leq 12$$ also.
```suggestion
We know that the lowest sum of two dice is 2 (a 1 on both dice), so $$n \geq 2$$ for sure. Similarly, the maximum is sum of two sixes, or 12, so $$n \leq 12$$ also. 
```
```suggestion
We know that the lowest sum of two dice is 2 (a 1 on both dice), so $$n \geq 2$$ for sure. Similarly, the maximum is the sum of two sixes, or 12, so $$n \leq 12$$ also. 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +N = \sum_n f(n)
```suggestion
N = \sum_n f(n),
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +P(n) = \frac{f(n)}{\displaystyle\sum_{n} f(n)}
```suggestion
P(n) = \frac{f(n)}{\displaystyle\sum_{n} f(n)}.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +Note that $$f(n)$$ does not necessarily have to be the frequency of $$n$$ - it could be any function which is _proportional_ to $$P(n)$$, and the above definition of $$P(n)$$ would still hold.
```suggestion
Note that $$f(n)$$ does not necessarily have to be the frequency of $$n$$ &ndash; it could be any function which is _proportional_ to $$P(n)$$, and the above definition of $$P(n)$$ would still hold. 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +And it's easy to check that the sum is now equal to 1, since
```suggestion
It's easy to check that the sum is now equal to 1, since
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\sum_n P(n) = \frac{\displaystyle\sum_{n}f(n)}{\displaystyle\sum_{n} f(n)} = 1
```suggestion
\sum_n P(n) = \frac{\displaystyle\sum_{n}f(n)}{\displaystyle\sum_{n} f(n)} = 1.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\mathbb{P}(a \leq n \leq b) = \sum_{n=a}^{b} P(n)
```suggestion
\mathbb{P}(a \leq n \leq b) = \sum_{n=a}^{b} P(n).
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +In that case, it doesn't make sense to ask what the probability is of $$x$$ being _exactly_ a particular number - there are infinite possible real numbers, after all, so the probability of $$x$$ bein
```suggestion
In that case, it doesn't make sense to ask what the probability is of $$x$$ being _exactly_ a particular number &ndash; there are infinite possible real numbers, after all, so the probability of $$x$$ being exactly any one of them is essentially zero! 
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +> the probability of a range of values is the _area_ of the region under the probability density curve which is within that range.
I feel like the quote here makes it less visible and also make me feel like it is coming from another source. Maybe bold it instead?

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\mathbb{P}(x_0 \leq x \leq x_0 + dx) = P(x)dx
```suggestion
\mathbb{P}(x_0 \leq x \leq x_0 + dx) = P(x)dx.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\mathbb{P}(a \leq x \leq b ) = \int_a^b P(x)dx
```suggestion
\mathbb{P}(a \leq x \leq b ) = \int_a^b P(x)dx.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\mathbb{P}(a \leq n \leq b) = \sum_{n=a}^{b} P(n)
```suggestion
\mathbb{P}(a \leq n \leq b) = \sum_{n=a}^{b} P(n).
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +And the fact that all probabilities must sum to 1 translates to
```suggestion
The fact that all probabilities must sum to 1 translates to
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +\int_D P(x)dx = 1
```suggestion
\int_D P(x)dx = 1.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +P(\mathbf{x}) = \frac{f(\mathbf{x})}{\int_D f(\mathbf{x})d\mathbf{x}}
```suggestion
P(\mathbf{x}) = \frac{f(\mathbf{x})}{\int_D f(\mathbf{x})d\mathbf{x}}.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +f(x) = e^{-x^2}
```suggestion
f(x) = e^{-x^2},
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +N = \int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}
```suggestion
N = \int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +and so we have a Gaussian probability distribution,
```suggestion
Now we have a Gaussian probability distribution,
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +P(x) = \frac{1}{N} e^{-x^2} = \frac{1}{\sqrt{\pi}} e^{-x^2}
```suggestion
P(x) = \frac{1}{N} e^{-x^2} = \frac{1}{\sqrt{\pi}} e^{-x^2}.
```

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +There are really only two rules that $$f(\mathbf{x})$$ must satisfy to be a candidate for a probability density distribution:
Why are we bolding x now?

2021-11-25 13:47 UTC, leios commented on contents/probability/distributions/distributions.md
> +$$
```suggestion
$$
\int_{S}f(\mathbf{x})d\mathbf{x} \geq 0.
$$ 
2. The following integral must be finite:
$$
\int_{D} f(\mathbf{x})d\mathbf{x}.
$$ 
```

2021-11-25 19:20 UTC, shudipto-amin commented on contents/probability/distributions/distributions.md
> +> the probability of a range of values is the _area_ of the region under the probability density curve which is within that range.
```suggestion
 __the probability of a range of values is the _area_ of the region under the probability density curve which is within that range.__ 
```

2021-11-25 19:21 UTC, shudipto-amin commented on contents/probability/distributions/distributions.md
> +In general, normalization can allow us to create a probability distribution out of almost any function $$f(x)$$.
```suggestion
In general, normalization can allow us to create a probability distribution out of almost any function $$f(\mathbf{x})$$. 
```

2021-11-25 19:23 UTC, shudipto-amin commented on contents/probability/distributions/distributions.md
> +There are really only two rules that $$f(\mathbf{x})$$ must satisfy to be a candidate for a probability density distribution:
I moved from specific 1D example to talking about general formulation, so x is bold to represent multidimensional coordinates.

2021-11-25 23:18 UTC, Amaras commented
I need to tell you two things @shudipto-amin.

First we receive a notification on the discord server after every single commit.
This gets overwhelming very quickly. So could you please commit suggestions in batches in the future? This applies to this chapter review and all future reviews.

Second, I have a few problems with your notation, since I come from a mathematical background, the main thing being that I have never seen the [2..12] notation used anywhere. I have already seen "double brackets" (something that looks like I[2, 12]I, I can't reproduce it better right now) and $ [2, 12] \cap \mathbb{N}$ for the integer interval [2, 12].
If you could point me to several mathematical sources that use your notation, I'll gladly read them and maybe even use it myself, but for now, it's not something I recognise easily.

2021-11-26 01:42 UTC, shudipto-amin commented
@Amaras 
> I need to tell you two things @shudipto-amin.
> 
> First we receive a notification on the discord server after every single commit. This gets overwhelming very quickly. So could you please commit suggestions in batches in the future? This applies to this chapter review and all future reviews.
> 
I'm sorry about that, I was adding from conversations where that seems to be the only option. Later, I did discover that option in the files tab, and started batching about half-way through. 

> Second, I have a few problems with your notation, since I come from a mathematical background, the main thing being that I have never seen the [2..12] notation used anywhere. I have already seen "double brackets" (something that looks like I[2, 12]I, I can't reproduce it better right now) and $ [2, 12] \cap \mathbb{N}$ for the integer interval [2, 12]. If you could point me to several mathematical sources that use your notation, I'll gladly read them and maybe even use it myself, but for now, it's not something I recognise easily.
I personally only discovered this notation recently - I normally see something like your example with $\mathbb{N}$. However, I thought this would be notationally simpler, since I explain it anyway. I also thought it would be a bit more familiar to people with some coding background, but I'm not really sure. The only public source I can remember right now is this [Wikipedia page](https://en.wikipedia.org/wiki/Interval_(mathematics)#Integer_intervals). If you think I should change it, I don't mind.

2021-11-26 08:59 UTC, Amaras commented
> I'm sorry about that, I was adding from conversations where that seems to be the only option. Later, I did discover that option in the files tab, and started batching about half-way through.

No problem, but keep that in mind for the future.

> I personally only discovered this notation recently - I normally see something like your example with $\mathbb{N}$. However, I thought this would be notationally simpler, since I explain it anyway. I also thought it would be a bit more familiar to people with some coding background, but I'm not really sure. The only public source I can remember right now is this [Wikipedia page](https://en.wikipedia.org/wiki/Interval_(mathematics)#Integer_intervals). If you think I should change it, I don't mind.

Yeah, that just tells me we need a mathematical notation chapter. I personally would prefer the ⟦a, b⟧ notation, but that's not a native latex symbol if I remember correctly.

2021-11-26 13:27 UTC, leios reviewed
Looks good! Mostly done, just have to look at the second half of Metropolis now!

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +So altogether there are $$3N$$ coordinates - making $$E(\mathbf{x})$$ a $$3N$$ dimensional function, which can be a computationally intensive calculation on it's own. But it doesn't end there!
```suggestion
So altogether there are $$3N$$ coordinates &ndash; making $$E(\mathbf{x})$$ a $$3N$$ dimensional function, which can be a computationally intensive calculation on it's own. But it doesn't end there!
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +Thus, the Boltzmann factor, $$\exp\left[-E(\mathbf{x})/T\right]$$, is also a 10D function. And so, to calculate $$Q$$, we would have to integrate the Boltzmann factor 10 times, one for each coordinat
```suggestion
Thus, the Boltzmann factor, $$\exp\left[-E(\mathbf{x})/T\right]$$, is also a 10D function. To calculate $$Q$$, we would have to integrate the Boltzmann factor 10 times, one for each coordinate,
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +Even with such poor resolution, the number of different combinations of positions is $$10^{50}$$ - a colossal number indeed.
```suggestion
Even with such poor resolution, the number of different combinations of positions is $$10^{50}$$ &ndash; a colossal number indeed. 
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> + With that speed, it would require $$10^{41}$$ seconds on a single processor to calculate $$Q$$ - which means that _even_ with all the processors in the world running in parallel (there could be bill
```suggestion
 With that speed, it would require $$10^{41}$$ seconds on a single processor to calculate $$Q$$, which means that _even_ with all the processors in the world running in parallel (there could be billions or trillions of them), calculating $$Q$$ would still take longer than the age of the universe by many orders of magnitude!
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +What's really powerful about the Metropolis approach is that you don't need to know the probability function itself - you just need a function which is _proportional_ to it.
```suggestion
What's really powerful about the Metropolis approach is that you don't need to know the probability function itself.
Instead, you just need a function which is _proportional_ to it. 
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +The Metropolis algorithm can bypass calculation of $$Q$$ altogether and use $$f(x)$$ to generate a distribution of $$x$$ which follows the probability density $$P(x)$$.
```suggestion
The Metropolis algorithm can bypass the calculation of $$Q$$ altogether and use $$f(x)$$ to generate a distribution of $$x$$ which follows the probability density $$P(x)$$. 
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +Finally, the Metropolis algorithm can be modified or implemented in other algorithms, and forms the basis of many advanced sampling algorithms.
```suggestion
Finally, the Metropolis algorithm can be modified or implemented in other methods, and forms the basis of many advanced sampling algorithms. 
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +P(\mathbf{x}) = \frac{f(\mathbf{x})}{\displaystyle\int_D f(\mathbf{x})d\mathbf{x}}
```suggestion
P(\mathbf{x}) = \frac{f(\mathbf{x})}{\displaystyle\int_D f(\mathbf{x})d\mathbf{x}},
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +\int_D P(\mathbf{x}) d\mathbf{x} = 1
```suggestion
\int_D P(\mathbf{x}) d\mathbf{x} = 1.
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +P(x) = \frac{e^{-x^2}}{\displaystyle\int_{-\infty}^{\infty} e^{-x^2} dx} = \frac{1}{\sqrt{\pi}} e^{-x^2}
```suggestion
P(x) = \frac{e^{-x^2}}{\displaystyle\int_{-\infty}^{\infty} e^{-x^2} dx} = \frac{1}{\sqrt{\pi}} e^{-x^2}.
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +E(\mathbf{x}) = E(x_1, y_1, z_1, x_2, y_2, z_2, ... ,x_N, y_N, z_N)
```suggestion
E(\mathbf{x}) = E(x_1, y_1, z_1, x_2, y_2, z_2, ... ,x_N, y_N, z_N),
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +P(\mathbf{x}) = \frac{\displaystyle \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right]} {Q}
```suggestion
P(\mathbf{x}) = \frac{\displaystyle \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right]} {Q},
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +Q = \int_D \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right] d\mathbf{x}
```suggestion
Q = \int_D \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right] d\mathbf{x}.
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +Q = \int_{x_1} \dots \int_{x_{10}} \exp\left[\frac{-E(x_1,\dots x_{10})}{T}\right]\ dx_1\dots dx_{10}
```suggestion
Q = \int_{x_1} \dots \int_{x_{10}} \exp\left[\frac{-E(x_1,\dots x_{10})}{T}\right]\ dx_1\dots dx_{10}.
```

2021-11-26 13:27 UTC, leios commented on contents/metropolis/metropolis.md
> +f(\mathbf{x}) = \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right]
```suggestion
f(\mathbf{x}) = \exp\left[{\displaystyle\frac{-E(\mathbf{x})}{T} } \right].
```

2021-11-26 17:39 UTC, Amaras commented
> @Amaras, I used this negative space hack, and it actually looks alright. Does this work?
Yeah, it looks good :)

2021-11-27 14:20 UTC, leios reviewed
Overall, very small changes to the text. Sorry to keep splitting this up into a bunch of smaller reviews.

I'll look at the code tomorrow and then I think the PR will be mostly ready to go!

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +Although the algorithm is not particularly efficient in just one dimension, it is much easier to understand and learn how to implement than in higher dimensions.
```suggestion
Although the algorithm is not particularly efficient in just one dimension, it is much easier to understand in one dimension than in multiple dimensions. 
```

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +And if global sampling is the goal, the process of exploration could be sped up by choosing larger step sizes for the walker, for example by choosing step size $$g$$ from an interval like $$(-3,3)$$
```suggestion
If global sampling is the goal, the process of exploration could be sped up by choosing larger step sizes for the walker, for example by choosing step size $$g$$ from an interval like $$(-3,3)$$ instead of $$(-1,1)$$. 
```

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +
There should be a comment here introducing the upcoming sections

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +where $$f(x)$$ is the function we know and is given by
```suggestion
where $$f(x)$$ is the same function we have shown above and is given by
```

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +For example, it can be a number chosen randomly from a discrete list, such as $$[ -3, -1, -1, +1, +1, +3]$$.
To be clear: this was meant to have multiple 1's, right?

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +In higher dimensions, the function should be spherically symmetric, such as multidimensional Gaussian function, $$e^{-(x^2 +y^2 + ...)}$$.
```suggestion
In higher dimensions, the function should be spherically symmetric, such as a multidimensional Gaussian function, $$e^{-(x^2 +y^2 + ...)}$$. 
```

2021-11-27 14:20 UTC, leios commented on contents/metropolis/metropolis.md
> +The following code puts everything together, and runs Metropolis algorithm for a number of  steps given by `num_steps`.
```suggestion
The following code puts everything together, and runs the Metropolis algorithm for a number of  steps given by `num_steps`. 
```

2021-11-27 17:03 UTC, shudipto-amin reviewed
Added a line to introduce subsections in " The Algorithm for a One D..." section. Not sure if it's sufficient. Addressed all other minor edits in a previous commit.

2021-11-27 17:03 UTC, shudipto-amin commented on contents/metropolis/metropolis.md
> +
Couldn't come up with anything other than the line (147) below. Feel free to throw in some suggestions.

2021-11-30 16:36 UTC, leios approved these changes
Overall, this looks good to me. There are just a few small changes to be made, so I am happy to go ahead and approve this! Good work and thanks for the patience!

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +where $$D$$ is the domain of $$P(\mathbf{x})$$, i.e., all possible values of the $$\mathbf{x}$$ for which $$P(\mathbf{x})$$ is defined;
```suggestion
where $$D$$ is the domain of $$P(\mathbf{x})$$, i.e., all possible values of the $$\mathbf{x}$$ for which $$P(\mathbf{x})$$ is defined.
```

I think this is a long run-on sentence

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +and $$f(\mathbf{x})$$ is some a function that is proportional to $$P(x)$$, such as a statistical frequency distribution, i.e., one that counts the number of occurences of each $$\mathbf{x}$$.
```suggestion
$$f(\mathbf{x})$$ is a function that is proportional to $$P(x)$$, such as a statistical frequency distribution which counts the number of occurences of each $$\mathbf{x}$$.
```

lots of i.e.s

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +This is because there is a long "barrier" of low probability region between the third peak and second peak.
```suggestion
This is because there is a long low probability region between the third peak and second peak that acts as a "barrier." 
```

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +How to choose $$g$$ is in itself a research field and depends on what the goal of the sampling is.
```suggestion
How to choose $$g$$ is in itself a research field and depends on what the goal of the sampling is. 
```
```suggestion
How to choose $$g$$ is, itself, a research field and depends on what the goal of the sampling is. 
```

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +Some methods even use an "adaptive" method where $$g$$ is "trained" on-the-fly using a learning algorithm!
```suggestion
Some techniques even use an "adaptive" method where $$g$$ is "trained" on-the-fly using a learning algorithm! 
```

2021-11-30 16:36 UTC, leios commented on contents/metropolis/code/python/metropolis.py
> +    xmin, xmax = -7, 7
Didn't we say in the chapter that our domain was from -10 to 10?

2021-11-30 16:36 UTC, leios commented on contents/metropolis/metropolis.md
> +    * Otherwise, __reject__ move, and set new position to current, $$x_{t+1} = x_t $$.
```suggestion
    * Otherwise, __reject__ move, and set new position to current position, $$x_{t+1} = x_t $$.
```

2021-12-02 18:57 UTC, shudipto-amin reviewed
Suggesting changes to address remaining comments by Leios, namely:
1. Changing the domain of x in python code,
2. Rewording the statement regarding finding an optimal $$g$$.

2021-12-02 18:57 UTC, shudipto-amin commented on contents/metropolis/code/python/metropolis.py
> +    xmin, xmax = -7, 7
```suggestion
    xmin, xmax = -10, 10
```

2021-12-02 18:57 UTC, shudipto-amin commented on contents/metropolis/metropolis.md
> +How to choose $$g$$ is in itself a research field and depends on what the goal of the sampling is.
```suggestion
The question of how to choose an optimal $$g$$ is a research area on its own, and depends largely on what the goal of the sampling is.
```

2021-12-03 13:25 UTC, merged