Stack queue in cpp
algorithm-archivists/algorithm-archive pull request #936
Opened 2021-11-14 08:35 UTC by ishwar00

2021-11-14 09:24 UTC, ShadowMitia requested changes
A good start, a few bugs to fix and a few things to iron out and you should be good.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +using namespace std;
It is not recommend to use `using namespace std;`, thought I think it's less of an issue in `.cpp` files.
See here : https://isocpp.org/wiki/faq/coding-standards#using-namespace-std

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        Node<T>* next;
I think we should be using smart pointers for this.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        Node<T>* _front;
I would try and avoid the use of `_`, it's not wrong, but there are cases where it's easy for it to become undefined behaviour that it would best to encourage other ways of renaming when there are conflicts with member names.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +            _front = rear = new Node<T>(0); // creating a dummy Node
You don't need a dummy Node if you have a `rear` pointer. 
This also causes bugs in your code, you can have an empty `queue` but using `front()` on it will give you a value, which is wrong. And that value can be modified and then lost when other values are pushed.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        T& front() const { return _front->value; }
I would also add the version with `T const& front() const`
This allows to use `front()` in cases where a `const`-reference is needed.

```suggestion
        T& front() const { return _front->value; }
        T const& front() const { return _front->value; }
```

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/stack.cpp
> +#include<iostream>
I won't repeat it here, but a lot of the comments in `queue` apply here too.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        // returning reference can very usefull if someone wants to modify _front element
```suggestion
```
I think this comment isn't necessary, a non-`const` reference can obviously be used to modify.

2021-11-14 09:24 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +    cout << "count: " << Q.size() << endl;
Replace `endl` with `\n`. `endl` does a newline and flush, which is not performant (and not required for everyline).

2021-11-14 09:33 UTC, ishwar00 commented on contents/stacks_and_queues/code/c++/queue.cpp
> +using namespace std;
thank you, i will use fully qualified names.

2021-11-15 19:33 UTC, henrikac commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        void push(const T& element) {
I believe the chapter and the other examples uses `enqueue` instead of `push`.

2021-11-15 19:33 UTC, henrikac commented on contents/stacks_and_queues/code/c++/queue.cpp
> +    }
Not sure if this is important but try to make this similar to the already implemented examples

2021-11-15 19:33 UTC, henrikac commented on contents/stacks_and_queues/code/c++/queue.cpp
> +    const char endl = '\n';
Why this? why not just use `std::endl`?

2021-11-15 19:36 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +    const char endl = '\n';
I agree `'\n` should be inlined.
`std::endl` adds a newline and does a flush, unless you really need realtime output, it's very inefficient to add it to every line.

2021-11-15 19:45 UTC, ishwar00 commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        void push(const T& element) {
[https://www.algorithm-archive.org/contents/stacks_and_queues/stacks_and_queues.html](url)
they use `push` here, so i just followed along.

2021-11-15 19:46 UTC, ShadowMitia commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        void push(const T& element) {
It does for stack but not for queue.

2021-11-15 20:00 UTC, ishwar00 commented on contents/stacks_and_queues/code/c++/queue.cpp
> +        void push(const T& element) {
for example, will often use `dequeue()` instead of `pop()` and `front()` instead of `top()`.

I read above lines in explanation, so i thought they kept `enqueue` as `push`, my bad.

2021-11-15 20:05 UTC, ishwar00 commented on contents/stacks_and_queues/code/c++/queue.cpp
> +    }
Yeah, i should have made them similar.

2022-01-12 08:49 UTC, ShadowMitia approved these changes
Looks good to me. Thank you!

2022-01-12 08:52 UTC, merged