Moce Code Reviewers from Wiki into the book
algorithm-archivists/algorithm-archive pull request #946
Opened 2021-11-28 18:02 UTC by ntindle

2021-11-28 18:08 UTC, ShadowMitia reviewed
Adding myself to a few languages I'm confident I can help

2021-11-28 18:08 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +c++ |
```suggestion
c++ | [@ShadowMitia]
```

2021-11-28 18:08 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +rust |
```suggestion
rust | [@ShadowMitia]
```

2021-11-28 18:08 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +javascript | [@ntindle]
```suggestion
javascript | [@ntindle] [@ShadowMitia]
```

2021-11-28 18:08 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +python | [@ntindle]
```suggestion
python | [@ntindle] [@ShadowMitia]
```

2021-11-28 18:09 UTC, ntindle commented on contents/code_reviews/code_reviewers.md
> +javascript | [@ntindle]
can you separate with a comma

2021-11-28 18:10 UTC, ntindle commented on contents/code_reviews/code_reviewers.md
> +python | [@ntindle]
can you separate with a comma

2021-11-28 18:10 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +python | [@ntindle]
Like this?

2021-11-28 18:35 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +nim |
```suggestion
nim |
ocaml | [@ShadowMitia]
```

2021-11-28 18:46 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +asm |
```suggestion
asm |
bash |
```

2021-11-28 18:52 UTC, ShadowMitia requested changes

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +emojicode |
```suggestion
c |
c# |
clojure |
coconut | [@amaras]
c++ | [@ShadowMitia]
crystal |
D |
dart |
elm |
emojicode |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +fortran | [@leios]
```suggestion
factor |
fortran | [@leios]
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +lua |
```suggestion
kotlin |
labview |
lolcode |
lisp |
lua |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +php |
```suggestion
php |
piet |
powershell |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +python | [@ntindle],[@ShadowMitia]
```suggestion
python | [@ntindle],[@ShadowMitia]
r |
racket |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +scala |
```suggestion
scala |
scheme |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +scratch | [@leios]
```suggestion
scratch | [@leios]
smalltask |
```

2021-11-28 18:52 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +typescript | [@ntindle]
```suggestion
typescript | [@ntindle]
v |
```

2021-11-29 10:50 UTC, Amaras reviewed
Adding myself now

2021-11-29 10:50 UTC, Amaras commented on contents/code_reviews/code_reviewers.md
>  python | [@ntindle],[@ShadowMitia]
```suggestion
python | [@ntindle],[@ShadowMitia],[@amaras]
```

2021-11-29 22:45 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +rust | [@ShadowMitia]
```suggestion
rust | [@ShadowMitia],[@PeanutbutterWarrior]
```

2021-11-29 22:45 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +python | [@ntindle],[@ShadowMitia],[@amaras]
```suggestion
python | [@ntindle],[@ShadowMitia],[@amaras],[@PeanutbutterWarrior]
```

2021-11-29 22:45 UTC, ShadowMitia commented on contents/code_reviews/code_reviewers.md
> +Scons | [@amaras]
```suggestion
Scons | [@amaras],[@PeanutbutterWarrior]
```

2021-11-29 22:46 UTC, ShadowMitia approved these changes

2021-11-29 22:48 UTC, merged