master -> main
algorithm-archivists/algorithm-archive pull request #953
Opened 2021-11-29 13:13 UTC by leios

I think the only thing we needed to change was `deploy.yml`, but I took the opportunity to also remove old travis infrastructure

2021-11-29 13:48 UTC, ShadowMitia requested changes

2021-11-29 13:48 UTC, ShadowMitia commented on .github/workflows/publish_container.yml
> +    - uses: actions/checkout@main
I don't think you're supposed to change that one.
```suggestion
    - uses: actions/checkout@master
```

2021-11-29 13:48 UTC, ShadowMitia commented on .github/workflows/publish_container.yml
> +      uses: elgohr/Publish-Docker-Github-Action@main
I don't think you're supposed to change that one.
```suggestion
      uses: elgohr/Publish-Docker-Github-Action@master
```

2021-11-29 16:55 UTC, ntindle reviewed
LGTM overall, keep in mind you will need to be quick about it running and we may need to merge another PR right after to trigger the deployments since when this is merged the main branch wont exist

2021-11-29 16:55 UTC, ntindle commented on contents/domain_coloring/domain_coloring.md.bak
> -
Contex on removal?

2021-11-29 16:55 UTC, ntindle commented on contents/flood_fill/flood_fill.md.bak
> -When I was completing my PhD, I had an idea to track superfluid vortices by using flood fill as a way to help mask out unnecessary features of the simulation.
Context on removal?

2021-11-29 16:55 UTC, ntindle commented on .github/workflows/publish_container.yml
> +    - uses: actions/checkout@main
Agreed

2021-11-29 16:55 UTC, ntindle commented on .github/workflows/publish_container.yml
> +      uses: elgohr/Publish-Docker-Github-Action@main
Agreed

2021-11-30 07:45 UTC, leios commented on contents/domain_coloring/domain_coloring.md.bak
> -
There were 2 `*.bak` files that were not meant to be committed. It was due to a temporary state in `aspell` for spell-checking I think

2021-11-30 07:49 UTC, leios commented
Ok, so to be clear, the best thing to do is:
1. Change the name to main
2. Merge this
3. update another PR to make sure the CI builds
4. If that branch works, then update all PRs?

2021-11-30 09:20 UTC, Amaras commented
If the branch is renamed successfully, all open PRs targets will be updated automatically as well.

2021-11-30 15:30 UTC, merged